version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-web-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-157febfkgywq4"
s3_prefix = "serverless-web-bot"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["BotFn=084882962555.dkr.ecr.us-west-1.amazonaws.com/serverlesswebbot79ce085d/botfn468d96ecrepo"]
